spring.datasource.url=jdbc:postgresql://localhost:3306/demodb
spring.datasource.username=root
spring.datasource.password=Ass122...
spring.jpa.database-platform=org.hibernate.dialect.MySQL5InnoDBDialect
spring.jpa.hibernate.ddl-auto=create
